### ISSUE TITLE
Dreame f9 / essential

### ISSUE THREAD

**Issue by pergolafabio** [Concentricc/xiaomi_vacuum#10]
Hi, just a question, will this also work for the dreame f9 or the xiaomi mi essential? 

I believe its a different model then the C1

**Comment by microfrost1** [comment]
No the F9 uses different commands. I have a repo for the F9 but I can't take any credit. [https://github.com/microfrost1/xiaomi_vacuum](https://github.com/microfrost1/xiaomi_vacuum)

**Comment by pergolafabio** [comment]
Cool, thnx for sharing, gonna ask community if someone tested it... If it works , i buy it
Seems cheaper then the C1 model, and seems better

**Comment by microfrost1** [comment]
Works for me. Been using it for about 3 weeks before uploading yesterday.

**Comment by pergolafabio** [comment]
Whats the difference between the xiaomi mi essential and the dreame F9 ? Are those different models?

**Comment by microfrost1** [comment]
They are different models. I went with the F9 due to the spec.

I was surprised the F9 and the 1C used different commands despite sharing the MIOT protocol. I can see the essential spec has been published but someone would need to compare it to see if it's compatible with either repo.

For what it's worth I'm really happy with the F9 but it's the first and only robot I've had.

**Comment by pergolafabio** [comment]
Are you sure?

There are 2 models from xiaomi
The xiaomi C1
And now..
The xiaomi mi mop essential...
I believe this essential is the same as the F9...

Also same height, like 8cm

Anyway, can you create no-go zones? I believe this was experimental and now removed in the app?

**Comment by pergolafabio** [comment]
I am referring to this model, I have no idea what's the difference bus with the dreame F9, only being sold cheaper...

https://mi-store.ch/produkt/xiaomi-eco-mi-vacuum-robot-mop-essential-white-skv4136gl-ean-6934177717161/

Those specs are the same and they look identical

**Comment by microfrost1** [comment]
The F9 has a bigger battery and dust bin size on first glance. I currently have the option for no go zones in the Xiaomi app. Haven't tried to add it to the integration though.

**Comment by pergolafabio** [comment]
Ok, thnx for sharing, gonna look up some more info...
I think the F9 is some kind of clone device, i am not if Xiaomi company is producing it ... Doesn't matter though

**Comment by pergolafabio** [comment]
ok, i compared, the dreame f9 vs xiaomi essential the dreame f9 has indeed a bigger battery / dustbin
the essential costs 160€ , the dreame f9 costs 176€ , so thats a good deal

but the dreame f9 is not really a xiaomi brand?

**Comment by microfrost1** [comment]
I'm pretty sure Xiaomi invested in Dreame and Dreame manufacturers all three of these.

**Comment by pergolafabio** [comment]
Ok, Dreame F9 is ordered... :-)

I also have a Xiaomi S5 , it doesn't give any conflict with your custom? Also, what's possible and what is not working yet?

And last, is there already a PR to make this an official component?


Thnx for all answers

**Comment by DavidConnack** [comment]
All basic commands work as well as zone cleaning.
Im not sure if this will work with the F9.

There is no plans to make this a PR for an official component as there is already a Xiaomi vacuum component and afaik the HA developers do not want another one but would rather want to compatibility from the exisiting component.

**Comment by pergolafabio** [comment]
yeah, doesnt need to be a new component, but if it the device would be added to the already excisting one, that would be wonderfull
is there aleady a WIP ?

**Comment by DavidConnack** [comment]
Development on that PR was not continued last i checked. The developers needed the integration to fit in with their entire project. [see](https://github.com/rytilahti/python-miio/pull/683#issuecomment-642963214)
I have no interest in trying to merge the 2. I created this component purely for my own needs as i wanted to use this vacuum.
Should anyone want to take develpoment of this further they are welcome too 😃
Ultimately I agree that there should be only one component, but for now this one works.

**Comment by pergolafabio** [comment]
ok, thnx for feedback!

**Comment by pergolafabio** [comment]
hey @microfrost1 

my dreame f9 arrived, i started clean the first time, but after he cleaned the floor, he stayed cleaning, he was going back to every room and touching all things,  the map was created correctly, but he never returned... after 15 min, i told him  manually to go back to the charger... then he went back instantly

any idea? did you also had that issue?

**Comment by microfrost1** [comment]
The first few cleans weren't optimal for me either. On a normal clean it does the main area and then goes around all the parameters. To be honest I rarely see it as mine is linked to presence detection and runs when nobody is gome.

I think the first cycles are learning ones and I vaguely remember the app stating a few days learning. Have you turned on map saving mode?

**Comment by pergolafabio** [comment]
Yeah, i have map saved mode turned on...
For test, i did a fresh clean i a small room, he did the clean about 3 times, 18 min for like 10m2


But indeed , I also think it's some kind of learning mode....
My roborock s50, does the job much better, but probably more location sensors...

Anyway, we will see after a few cleans...

Do you always do the same start command to start fresh clean? Or zone/room cleaning?

Maybe it's better todo zone/room cleaning each time? Instead of a start command , maybe he will always try to recognize the room again?

Also, can you save multiple maps? What will happen if map saved mode is on, and I let him clean another floor without a charger?

**Comment by microfrost1** [comment]
My last clean did 11m2 in 10mins. I use a combo of start clean and targeted zones. I basically have input booleans that queue the clean for when we leave the house which will either be a room or the whole floor.

Regarding multiple maps I haven't tried another floor yet but I don't see any option that suggests it can support it well. I've only can the bot about 4 weeks other than it getting stuck once it hasn't had much attention beyond the first week.

**Comment by pergolafabio** [comment]
Yeah, need to play with it, works differentlybthen my other xiaomi... But for 172€ , it's not expensive either ;-)

Do you see a difference if you clean all rooms VS a start clean? Did you ever try that ? My first opinion is that a zone / room (full map)  clean is quicker then a start clean

**Comment by pergolafabio** [comment]
hey @microfrost1 

i am using your custom component, is zone cleaning also working with your custom?
also,  wanted to try out , so downloaded and installed that custom .apk from here : https://www.kapiba.ru/2017/11/mi-home.html 

started zone cleaning, it should create a vevs folder with logs
i see indeed a vevs folder, but all 3 subfolders are empty,.. no log files
how did you succeed extracting coordinates?

thnx

**Comment by microfrost1** [comment]
Hi,

Yes zone cleaning works.

I didn't go down the APK route as I don't like installing compiled code that I can't validate.

I sniffed the traffic into wireshark then decoded the packets to get the coordinates. I went down  complex route so I could establish what commands were required so I believe there are easier routes for you.

What did help is that as soon as you fire valid coordinates across, the app shows the borders on the map.

Thanks

**Comment by pergolafabio** [comment]
Ok, will do it with some trial and error..

Is there no support for room cleaning instead of coordinates? That would be a lot easier

**Comment by pergolafabio** [comment]
and btw @microfrost1 , did you use some wireshark on your android? or PC software? can you explain how you did the decode?

otherwise gonna with just sending random zones, and then looking in app and modifiyng, a little bit of work :) , is the starting point also 25500,25500 ? like roborock?
