### ISSUE TITLE
 No 'version' key in the manifest file for custom integration 'xiaomi_vacuum'

### ISSUE THREAD

**Issue by oopiicaa** [Concentricc/xiaomi_vacuum#18]
After upgrading to HA Core 2021.3.0, this error shows up in logs:
`No 'version' key in the manifest file for custom integration 'xiaomi_vacuum'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'xiaomi_vacuum'`

xiaomi_vacuum integration installed through HACS

**Comment by Radlagerkok** [comment]
+ With the latest home assistant update:
https://www.home-assistant.io/blog/2021/03/03/release-20213/#breaking-changes
Custom integrations: Version warning

Custom integrations now require a version key in their manifest file, this also means that all custom integrations now require a manifest file.

If you are using a legacy custom integration like custom_components/awesome.py this now needs to move to custom_components/awesome/__init__.py so you can add custom_components/awesome/manifest.json to it.

For more information about integration, manifests have a look here: https://developers.home-assistant.io/docs/creating_integration_manifest

For now, this will create a warning on startup. But this will eventually be blocked from loading if it’s missing a version in the manifest.

If you see these warnings, please report the issue with the author of that custom integration.

**Comment by DavidConnack** [comment]
Added a version to manifest.json.
