### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by RaftTone** [Concentricc/xiaomi_vacuum#23]
Hey, I was trying to integrate into Homeassistant and got this error. Is there a way to fix it on my side maybe? Thanks

WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'xiaomi_vacuum'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'xiaomi_vacuum'
ERROR (MainThread) [homeassistant.components.homeassistant] Platform error vacuum.xiaomi_vacuum - No module named 'miio'

**Comment by kzvdar42** [comment]
How did you solved the `No module named 'miio'` Error?

**Comment by RaftTone** [comment]
> How did you solved the `No module named 'miio'` Error?

Sorry I don't remember :( I'm using my 1C with Homebridge directly now with other plugin. Had to use HA for some time and connect it to Homekit when there were no direct solutions for my case.
