### ISSUE TITLE
License

### ISSUE THREAD

**Issue by stek29** [Concentricc/xiaomi_vacuum#25]
What's the license for code of this custom integration?
I'd like to use parts of this code for python-miio which is licensed under GPL

**Comment by DavidConnack** [comment]
Hi

I have not added a license.
What do you want to use it for?
I will add one now?

**Comment by stek29** [comment]
@Concentricc I was thinking of using code from this repo instead of one in python-miio repo, but ended up writing it from scratch while looking both into your code and original repo

I'm trying to get Dreame vacuum supported in homeassistant without custom components, see rytilahti/python-miio#1059
