### ISSUE TITLE
Great job...finally...but many errors in the log

### ISSUE THREAD

**Issue by hassioborgia** [Concentricc/xiaomi_vacuum#3]
Hi, congratulations. Finally a partial integration in HA. However, there are many errors in the registry. Here are a few.

1. 

Logger: custom_components.xiaomi_vacuum.miio.device
Source: custom_components/xiaomi_vacuum/miio/device.py:218
Integration: Xiaomi Vacuum
First occurred: 23 giugno 2020, 21:01:02 (931 occurrences)
Last logged: 10:10:57

Unable to request properties [{'did': 'battery', 'siid': 2, 'piid': 1}, {'did': 'state', 'siid': 2, 'piid': 2}, {'did': 'error', 'siid': 3, 'piid': 1}, {'did': 'status', 'siid': 3, 'piid': 2}, {'did': 'brush_left_time', 'siid': 26, 'piid': 1}, {'did': 'brush_life_level', 'siid': 26, 'piid': 2}, {'did': 'filter_life_level', 'siid': 27, 'piid': 1}, {'did': 'filter_left_time', 'siid': 27, 'piid': 2}, {'did': 'brush_left_time2', 'siid': 28, 'piid': 1}, {'did': 'brush_life_level2', 'siid': 28, 'piid': 2}, {'did': 'operating_mode', 'siid': 18, 'piid': 1}, {'did': 'area', 'siid': 18, 'piid': 4}, {'did': 'timer', 'siid': 18, 'piid': 5}, {'did': 'fan_speed', 'siid': 18, 'piid': 6}]
Unable to request properties [{'did': 'last_clean', 'siid': 18, 'piid': 13}, {'did': 'total_clean_count', 'siid': 18, 'piid': 14}, {'did': 'total_area', 'siid': 18, 'piid': 15}, {'did': 'total_log_start', 'siid': 18, 'piid': 16}, {'did': 'button_led', 'siid': 18, 'piid': 17}, {'did': 'clean_success', 'siid': 18, 'piid': 18}, {'did': 'life_sieve', 'siid': 19, 'piid': 1}, {'did': 'life_brush_side', 'siid': 19, 'piid': 2}, {'did': 'life_brush_main', 'siid': 19, 'piid': 3}, {'did': 'dnd_enabled', 'siid': 20, 'piid': 1}, {'did': 'dnd_start_time', 'siid': 20, 'piid': 2}, {'did': 'dnd_stop_time', 'siid': 20, 'piid': 3}, {'did': 'map_view', 'siid': 23, 'piid': 1}, {'did': 'audio_volume', 'siid': 24, 'piid': 1}]
Unable to request properties [{'did': 'audio_language', 'siid': 24, 'piid': 3}, {'did': 'timezone', 'siid': 25, 'piid': 1}]

2.

Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_vacuum/miio/miot_device.py:65
First occurred: 23 giugno 2020, 21:01:02 (623 occurrences)
Last logged: 10:11:02

Update for vacuum.cincin fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/xiaomi_vacuum/vacuum.py", line 253, in update
    state = self._vacuum.status()
  File "/config/custom_components/xiaomi_vacuum/miio/dreamevacuum.py", line 259, in status
    return self.get_properties_for_dataclass(DreameStatus)
  File "/config/custom_components/xiaomi_vacuum/miio/miot_device.py", line 66, in get_properties_for_dataclass
    property_mapping, max_properties=cls._max_properties
  File "/config/custom_components/xiaomi_vacuum/miio/miot_device.py", line 65, in <dictcomp>
    for prop in self.get_properties_for_mapping(
TypeError: list indices must be integers or slices, not str

**Comment by DavidConnack** [comment]
you probably have something wrong in your config.
These errors are from the python library that interacts with the device, not home assistant.
