### ISSUE TITLE
Not compliant with HACS

### ISSUE THREAD

**Issue by csrui** [Concentricc/xiaomi_vacuum#4]
Adding the repository as custom repository to HACS throws the following error message.

`Repostitory structure for master is not compliant`.

Home Assistant: 0.112.2
HACS: 1.1.2

**Comment by DavidConnack** [comment]
This is currently not intended to be used with HACS as i dont use it.
If you would like to make it compatible, feel free to submit a PR.

**Comment by DavidConnack** [comment]
@csrui you can try in now i have merged the PR

**Comment by csrui** [comment]
Sorry it took a while. At night I couldn't get it working because of my son's bedtime.

I have now tested it with success. First complete run using HACS.
