### ISSUE TITLE
Status of error message

### ISSUE THREAD

**Issue by htmltiger** [Concentricc/xiaomi_vacuum#6]
Is it possible to get the error message when the vacuum get stuck or stops?

I can see that it is in the dreamevacuum.py but is there any way it can be added to the status error?

Thanks

```
class Error(Enum):
    NoError = 0
    Drop = 1
    Cliff = 2
    Bumper = 3
    Gesture = 4
    Bumper_repeat = 5
    Drop_repeat = 6
    Optical_flow = 7
    No_box = 8
    No_tankbox = 9
    Waterbox_empty = 10
    ...
```

**Comment by DavidConnack** [comment]
Hi

I have added this into the component.
![image](https://user-images.githubusercontent.com/47108996/95975494-89dd8e80-0e16-11eb-8290-c8aa7cfda338.png)
