### ISSUE TITLE
Zone cleaning status

### ISSUE THREAD

**Issue by Radlagerkok** [Concentricc/xiaomi_vacuum#9]
Hi. I start zone cleaning and the status of the vacuum cleaner goes to idle. How to make the status change to cleaning during zonal cleaning? Thank you

**Comment by DavidConnack** [comment]
Hi
Assumin that you have the correct coordinates for your zone, once triggered from home assistant, the vacuum should start the zone cleaning.
How are you triggering the zone cleanup, and have you got the correct coordinates from the app?

**Comment by snowgumrd** [comment]
I think hes referring specifically to the status still showing idle. Mine does the same thing. The vac goes to the zone and starts cleaning my in HA, the vacuum card shows the status as idle.

**Comment by Radlagerkok** [comment]
Yes, status still showing idle when the robot vacuum cleaner does zone cleaning.

**Comment by ErikT80** [comment]
I noticed the same! Would love to not trigger any cleaning automation when the vacuum is has state cleaning. But because the state still is 'idle' when performing a zoned-cleanup this doesn't work.

**Comment by crozo5** [comment]
I have the same issue

**Comment by nick7zmail** [comment]
Hello. How can i get zone coordinates? 
Please tell me...
